name: Lyttejeger
options:
  bundleIdPrefix: no.lene
  deploymentTarget:
    iOS: "26.0"
  xcodeVersion: "26.2"
  generateEmptyDirectories: true
settings:
  base:
    SWIFT_VERSION: "6.0"
    TARGETED_DEVICE_FAMILY: "1"
    INFOPLIST_FILE: Lyttejeger/Info.plist
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    PRODUCT_BUNDLE_IDENTIFIER: no.lene.lyttejeger
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_STRICT_CONCURRENCY: complete
    ENABLE_USER_SCRIPT_SANDBOXING: true
targets:
  Lyttejeger:
    type: application
    platform: iOS
    sources:
      - path: Lyttejeger
        excludes:
          - "**/.DS_Store"
    resources:
      - path: Lyttejeger/Resources/Assets.xcassets
      - path: Lyttejeger/Resources/Fonts
        buildPhase: resources
    settings:
      base:
        INFOPLIST_FILE: Lyttejeger/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: no.lene.lyttejeger
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 8NW62A7PRA
        SUPPORTED_PLATFORMS: "iphonesimulator iphoneos"
        SUPPORTS_MACCATALYST: false
    info:
      path: Lyttejeger/Info.plist
      properties:
        UILaunchScreen:
          UIColorName: LaunchBackground
        UIBackgroundModes: [audio]
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UIAppFonts:
          - DMMono-Light.ttf
          - DMMono-Regular.ttf
          - DMMono-Medium.ttf
        CFBundleDisplayName: Lyttejeger
  LyttejegerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: LyttejegerTests
    dependencies:
      - target: Lyttejeger
  LyttejegerUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: LyttejegerUITests
    dependencies:
      - target: Lyttejeger
schemes:
  Lyttejeger:
    build:
      targets:
        Lyttejeger: all
    run:
      config: Debug
    test:
      targets:
        - LyttejegerTests
        - LyttejegerUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
